// File generated by FlutterFire CLI.
// This is a placeholder file. Run `flutterfire configure` to generate the actual file.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'run `flutterfire configure` to generate this file.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'run `flutterfire configure` to generate this file.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'run `flutterfire configure` to generate this file.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'run `flutterfire configure` to generate this file.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace these placeholder values with your actual Firebase configuration

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqvauuEv7tSfgTVxS-MDpY9LDoV1lTuvk',
    appId: '1:872481007760:android:702f33283a06b25cb41015',
    messagingSenderId: '872481007760',
    projectId: 'interview-buddy-128dc',
    storageBucket: 'interview-buddy-128dc.firebasestorage.app',
  );

  // Run `flutterfire configure` to generate this file with your project's values

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbia2BukZZWaPIWgysiHJCbc2NcIYmU8c',
    appId: '1:872481007760:ios:6df02173d762bd90b41015',
    messagingSenderId: '872481007760',
    projectId: 'interview-buddy-128dc',
    storageBucket: 'interview-buddy-128dc.firebasestorage.app',
    iosBundleId: 'com.interviewbuddy.interviewBuddy',
  );

}